module.exports = module.exports || {};

module.exports["scrollbar"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '\t<template>\n\t\t<style>\n\t\t.scroll-bar {\n\t\t\twidth: 15px;\n\t\t\tposition: absolute;\n\t\t\ttop:0;\n\t\t\tbottom:0;\n\t\t\tbackground-color: lightgrey;\n\t\t}\n\t\t.scroll-bar-gutter {\n\t\t\tposition: absolute;\n\t\t\ttop: 0%;\n\t\t\tbottom: 0%;\n\t\t\tright: 0%;\n\t\t\tleft: 0%;\n\t\t\tmargin-top: 15px;\n\t\t\tmargin-bottom: 35px;\n\t\t}\n\t\t.scroll-bar.horizontal {\n\t\t\theight: 15px;\n\t\t\twidth: 100%;\n\t\t\tposition: absolute;\n\t\t\tleft:0;\n\t\t\tright: 100%;\n\t\t\ttop:100%;\n\t\t}\n\n\t\t.horizontal .scroll-bar-gutter {\n\t\t\tposition: absolute;\n\t\t\ttop: 0%;\n\t\t\tbottom: 0%;\n\t\t\tright: 0%;\n\t\t\tleft: 0%;\n\t\t\tmargin-top: 0px;\n\t\t\tmargin-bottom: 0px;\n\t\t\tmargin-left: 15px;\n\t\t\tmargin-right: 35px;\n\t\t}\n\n\t\t.scroll-bar-up{\n\t\t\tposition: absolute;\n\t\t\ttop: 0;\n\t\t\tleft: 0;\n\t\t\twidth: 15px;\n\t\t\theight: 15px;\n\t\t\tbackground-color: darkgrey;\n\t\t}\n\n\t\t.scroll-bar.horizontal .scroll-bar-up{\n\t\t\tposition: absolute;\n\t\t\ttop: 0;\n\t\t\tright: 0;\n\t\t\tleft: auto;\n\t\t\twidth: 15px;\n\t\t\theight: 15px;\n\t\t\tbackground-color: darkgrey;\n\t\t}\n\n\t\t.scroll-bar-thumb {\n\t\t\tbackground-color: gray;\n\t\t\twidth: 15px;\n\t\t\theight: 20px;\n\t\t\ttop: 0;\n\t\t\tleft: 0px;\n\t\t\tposition: absolute;\n\t\t}\n/*\t\t.scroll-bar-thumb:mousedown {\n\t\t\t\n\t\t}*/\n\t\t\n\t\t.scroll-bar.horizontal .scroll-bar-thumb {\n\t\t\theight: 15px;\n\t\t\twidth: 20px;\n\t\t\tleft: 0px;\n\t\t\ttop: 0;\n\t\t\tposition: absolute;\n\t\t}\n\n\t\t.scroll-bar-down{\n\t\t\tposition: absolute;\n\t\t\tright: 0;\n\t\t\tbottom: 0;\n\t\t\twidth: 15px;\n\t\t\theight: 15px;\n\t\t\tbackground-color: darkgrey;\n\t\t}\n\t\t.scroll-bar.horizontal .scroll-bar-down{\n\t\t\tposition: absolute;\n\t\t\tleft: 0;\n\t\t\twidth: 15px;\n\t\t\theight: 15px;\n\t\t\tbackground-color: darkgrey;\n\t\t}\n\n\t\t</style>\n\t\t<div class="scroll-bar">\n\t\t\t<div class="scroll-bar-up"></div>\n\t\t\t<div class="scroll-bar-gutter">\n\t\t\t\t<div class="scroll-bar-thumb" draggable="false"></div>\n\t\t\t</div>\n\t\t\t<div class="scroll-bar-down"></div>\n\t\t</div>\n\t</template>\n';

}
return __p
};